### ISSUE TITLE
FR: realtime oversight

### ISSUE THREAD

**Issue by gerroon** [classicsc/syncthingmanager#1]
Hi
I realize that your tool is initially an commandline tool to control syncthing but I feel like it can expand beyond that. I was dreaming about a complimentary syncthing tool that works on the termianl that functions like atop or htop where it shows what is going o with syncthing and files, more like a terminal version of web gui. 

Maybe stman can bring this kind of functionality?

thanks

**Comment by classicsc** [comment]
Thanks for the suggestion. I don't want to bring live monitoring to this package since one of the main purposes is to have commands suitable for shell scripting, but it would certainly be useful from time to time. You may want to look into the curses library, which is used to make applications like htop.
